### ISSUE TITLE
Incompatible with the latest crystal version(0.32.0)

### ISSUE THREAD

**Issue by Gaabe** [cubos/sdkgen#61] opened 2019-12-13 18:19 UTC
As the title says, sdkgen doesn't work with the latest version of crystal(0.32.0).
It seems that this version limited the maximum size of tuples, which makes the sdkgen scripts fail with errors like:

`tuple size cannot be greather than 300 (size is 639)`

The erros points to crystal's default library at:

`/src/string.cr:4536:27`

![image](https://user-images.githubusercontent.com/8263465/70822248-dd78e900-1dbb-11ea-8572-d1293b1fbda0.png)

Steps to reproduce:
Just run any sdkgen project with the latest crystal version.

**Comment by dgadelha** [comment] 2019-12-13 18:27
This issue was caused by a breaking change in Crystal (https://github.com/crystal-lang/crystal/issues/8576). A fix was implemented in https://github.com/crystal-lang/crystal/pull/8581 and it should be released on version [0.32.1](https://github.com/crystal-lang/crystal/milestone/41). The workaround for now is to use [0.31.1](https://github.com/crystal-lang/crystal/releases/tag/0.31.1).

**Comment by lbguilherme** [comment] 2020-02-09 12:42
Crystal 0.32.1 has been released. Closing this.

**Closed by lbguilherme** 2020-02-09 12:42 UTC
